# Generated by Django 6.0.3 on 2026-05-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_driver_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredToda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toda_number', models.CharField(max_length=20, unique=True)),
                ('driver_name', models.CharField(max_length=100)),
                ('vehicle_plate', models.CharField(max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
