# Generated by Django 6.0.3 on 2026-05-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_registeredtoda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredtoda',
            name='registration_date',
            field=models.DateTimeField(),
        ),
    ]
