# Generated by Django 6.0.3 on 2026-05-21 13:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_registeredtoda_registration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toda_name', models.CharField(max_length=100)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
