# Generated by Django 6.0.3 on 2026-05-21 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_toda'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredtoda',
            name='toda',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='station', to='api.toda'),
            preserve_default=False,
        ),
    ]
