# Generated by Django 6.0.3 on 2026-05-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_registeredtoda_toda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toda',
            old_name='toda_name',
            new_name='name',
        ),
    ]
