# Generated by Django 6.0.3 on 2026-05-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_toda_name_toda_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='toda',
            name='color',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
