# Generated by Django 6.0.3 on 2026-06-24 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_driver_user_alter_passenger_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='contact_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='toda_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toda_drivers', to='api.toda'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='emergency_contact_number',
            field=models.IntegerField(),
        ),
    ]
