# Generated by Django 6.0.3 on 2026-06-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_driver_contact_number_driver_toda_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='contact_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='contact_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='emergency_contact_number',
            field=models.CharField(max_length=11),
        ),
    ]
