# Generated by Django 6.0.3 on 2026-07-02 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_booking_end_address_booking_start_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
