# Generated by Django 6.0.3 on 2026-07-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_stop_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='toda',
            name='prefix',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
