# Generated by Django 6.0.3 on 2026-07-13 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_toda_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
