# Generated by Django 6.0.3 on 2026-07-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_driver_rating_passenger_rating_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='feedback',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
