# Generated by Django 6.0.3 on 2026-07-30 13:07

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rate_booking_rate_created_at_rate_rater_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='toda_station',
            new_name='toda_boundary',
        ),
        migrations.AlterField(
            model_name='registeredtoda',
            name='toda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='api.toda'),
        ),
        migrations.CreateModel(
            name='TodaStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('toda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='api.toda')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='toda_stations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toda_station_drivers', to='api.todastation'),
        ),
    ]
