# Generated by Django 6.0.3 on 2026-08-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_toda_station_driver_toda_boundary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='toda_stations',
            new_name='toda_station',
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_plate',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
