# Generated by Django 6.0.3 on 2026-08-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_toda_stations_driver_toda_station_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='franchise_permit_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_number',
        ),
    ]
