# Generated by Django 6.0.3 on 2026-08-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_driver_franchise_permit_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='routes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
