# Generated by Django 6.0.3 on 2026-08-03 22:40

import api.features.reports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_booking_routes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='toda_boundary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='toda_drivers', to='api.toda'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='toda_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='toda_station_drivers', to='api.todastation'),
        ),
        migrations.AlterField(
            model_name='registeredtoda',
            name='toda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='api.toda'),
        ),
        migrations.AlterField(
            model_name='todastation',
            name='toda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='api.toda'),
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_lat', models.FloatField()),
                ('gps_lng', models.FloatField()),
                ('incident_types', models.CharField(choices=[('accident', 'Accident'), ('overcharging', 'Overcharging'), ('reckless_driving', 'Reckless Driving'), ('harassment', 'Harassment'), ('lost_item', 'Lost Item'), ('others', 'Others')], default='none', max_length=20)),
                ('injured_party', models.CharField(choices=[('passenger', 'Me (Passenger)'), ('driver', 'Driver'), ('others', 'Others'), ('none', 'None')], default='none', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_reports', to='api.booking')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=api.features.reports.models.incident_evidence_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='api.incidentreport')),
            ],
        ),
    ]
