# Generated by Django 6.0.3 on 2026-08-03 23:14

import api.features.reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_driver_toda_boundary_alter_driver_toda_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentevidence',
            name='file',
            field=models.ImageField(upload_to=api.features.reports.models.incident_evidence_path),
        ),
    ]
