# Generated by Django 6.0.3 on 2026-08-06 18:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_incidentevidence_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='gps_lat',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='gps_lng',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, geography=True, srid=4326),
            preserve_default=False,
        ),
    ]
