# Generated by Django 6.0.3 on 2026-08-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_incidentreport_gps_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.CharField(choices=[('regular', 'REGULAR'), ('special', 'SPECIAL')], default='regular', max_length=10),
        ),
    ]
