# Generated by Django 6.0.3 on 2026-08-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BLACKLISTED', 'Blacklisted')], default='ACTIVE', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BLACKLISTED', 'Blacklisted')], default='ACTIVE', max_length=50),
        ),
    ]
