# Generated by Django 6.0.3 on 2026-09-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_passenger_status_alter_driver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='toda',
            name='base_fare',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
